### ISSUE TITLE
Please consider adding space for Saturday morning slides

### ISSUE THREAD

**Issue by claremacrae** [brycelelbach/cppnow_presentations_2016#7]
i.e. if Jon had any slides for 'C++ Today: The Beast is Back', could they be added?

(I'm assuming there weren't any slides for 'Library in a week' and 'Future of Boost'?

**Comment by brycelelbach** [comment]
Yah, I'll do this.

On Wed, May 18, 2016 at 3:12 PM, Clare Macrae notifications@github.com
wrote:

> i.e. if Jon had any slides for 'C++ Today: The Beast is Back', could they
> be added?
> 
> (I'm assuming there weren't any slides for 'Library in a week' and 'Future
> of Boost'?
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/brycelelbach/cppnow_presentations_2016/issues/7

## 

Bryce Adelstein Lelbach aka wash

## Lawrence Berkeley National Laboratory

**Comment by claremacrae** [comment]
I'm thinking this should be closed, as now not worth doing after so long...
